import { FileText, Truck, Receipt, LucideIcon } from "lucide-react";
import { VoucherType, VoucherStatus } from "../types/voucher";

/**
 * Get human-readable label for voucher type
 */
export function getVoucherTypeLabel(type: VoucherType): string {
  const labels: Record<VoucherType, string> = {
    invoice: "Factura",
    delivery_note: "Remito",
    receipt: "Recibo",
  };
  return labels[type];
}

/**
 * Get Lucide icon component for voucher type
 */
export function getVoucherTypeIcon(type: VoucherType): LucideIcon {
  const icons: Record<VoucherType, LucideIcon> = {
    invoice: FileText,
    delivery_note: Truck,
    receipt: Receipt,
  };
  return icons[type];
}

/**
 * Get short code for voucher type (for badges)
 */
export function getVoucherTypeCode(type: VoucherType): string {
  const codes: Record<VoucherType, string> = {
    invoice: "F",
    delivery_note: "R",
    receipt: "Rec",
  };
  return codes[type];
}

/**
 * Format voucher number with proper styling
 * e.g., "F-000042" -> "F-000042"
 */
export function formatVoucherNumber(number: string): string {
  return number;
}

/**
 * Get status label
 */
export function getVoucherStatusLabel(status: VoucherStatus): string {
  const labels: Record<VoucherStatus, string> = {
    active: "Activo",
    voided: "Anulado",
  };
  return labels[status];
}

/**
 * Get color class for voucher status
 */
export function getVoucherStatusColor(status: VoucherStatus): string {
  const colors: Record<VoucherStatus, string> = {
    active: "text-success",
    voided: "text-danger",
  };
  return colors[status];
}

/**
 * Get background color class for voucher status badge
 */
export function getVoucherStatusBgColor(status: VoucherStatus): string {
  const colors: Record<VoucherStatus, string> = {
    active: "bg-success/10",
    voided: "bg-danger/10",
  };
  return colors[status];
}

/**
 * Get border color class for voucher status badge
 */
export function getVoucherStatusBorderColor(status: VoucherStatus): string {
  const colors: Record<VoucherStatus, string> = {
    active: "border-success/30",
    voided: "border-danger/30",
  };
  return colors[status];
}

/**
 * Get description/help text for voucher type
 */
export function getVoucherTypeDescription(type: VoucherType): string {
  const descriptions: Record<VoucherType, string> = {
    invoice: "Documento fiscal con datos completos del cliente y negocio",
    delivery_note: "Comprobante de entrega con cantidades (sin precios)",
    receipt: "Comprobante de pago - solo para órdenes pagadas",
  };
  return descriptions[type];
}

/**
 * Format date to localized string
 */
export function formatVoucherDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString("es-AR", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

/**
 * Sort vouchers by type order (invoice first, then delivery_note, then receipt)
 */
export function sortVouchersByType<T extends { type: VoucherType }>(
  vouchers: T[]
): T[] {
  const typeOrder: Record<VoucherType, number> = {
    invoice: 1,
    delivery_note: 2,
    receipt: 3,
  };
  return [...vouchers].sort((a, b) => typeOrder[a.type] - typeOrder[b.type]);
}

/**
 * Check if receipt can be generated for an order
 * Receipts can only be generated for paid orders
 */
export function canGenerateReceipt(paymentStatus: string): boolean {
  return paymentStatus === "Pagado";
}

/**
 * Get default voucher types based on settings
 */
export function getDefaultVoucherTypes(
  settings?: {
    autoGenerateInvoice?: boolean;
    autoGenerateDeliveryNote?: boolean;
    autoGenerateReceipt?: boolean;
  } | null,
  paymentStatus?: string
): VoucherType[] {
  const defaults: VoucherType[] = [];

  if (settings?.autoGenerateInvoice) {
    defaults.push("invoice");
  }
  if (settings?.autoGenerateDeliveryNote) {
    defaults.push("delivery_note");
  }
  if (settings?.autoGenerateReceipt && paymentStatus === "Pagado") {
    defaults.push("receipt");
  }

  return defaults;
}
