// Voucher types for multiple vouchers feature

export type VoucherType = 'invoice' | 'delivery_note' | 'receipt';
export type VoucherStatus = 'active' | 'voided';

export interface Voucher {
  _id: string;
  order: string;
  type: VoucherType;
  number: string;
  sequentialNumber: number;
  filePath: string;
  fileUrl?: string;
  status: VoucherStatus;
  voidReason?: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface VoucherCounter {
  _id: string;
  tenant: string;
  type: VoucherType;
  prefix: string;
  lastNumber: number;
  year: number;
}

export interface VoucherConfig {
  invoicePrefix: string;
  deliveryNotePrefix: string;
  receiptPrefix: string;
  nextInvoiceNumber: number;
  nextDeliveryNoteNumber: number;
  nextReceiptNumber: number;
  annualResetEnabled: boolean;
  autoGenerateInvoice: boolean;
  autoGenerateDeliveryNote: boolean;
  autoGenerateReceipt: boolean;
}

export interface GenerateVouchersRequest {
  types: VoucherType[];
  generatePdf?: boolean;
}

export interface GenerateVouchersResponse {
  vouchers: Voucher[];
  generatedAt: string;
}

export interface VoidVoucherRequest {
  reason: string;
}

export interface VoidVoucherResponse {
  voucher: Voucher;
  message: string;
}

export interface VouchersByOrderResponse {
  vouchers: Voucher[];
}
